{% set name = "gravelamps" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/link/pre-merger-software/gravelamps/-/archive/{{ version }}/gravelamps-{{ version }}.tar.gz
  sha256: 747cee022662821ac822c1f5dfdada797bb5c0d3795ec1f2e711af83aa3fe378
build:
  entry_points:
    - gravelamps_inference=gravelamps.inference:main
    - gravelamps_generate_lens=gravelamps.generate_lens:main
    - gravelamps_combine_lens=gravelamps.combine_lens:main
    - gravelamps_joint_model_selection=gravelamps.joint_model_selection:main
  number: 0
  skip: true  # [win or py<=39 or py >= 312]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - cmake
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - libflint
    - libboost-headers
    - {{ compiler('cxx') }}  # [osx]
    - numpy <2.4.0
  run:
    - python
    - asimov
    - astropy-base <7.0
    - attrs
    - bilby <2.7.0
    - bilby_pipe >=1.3.0
    - python-htcondor
    - {{ pin_compatible('numpy') }}
    - lalsuite

test:
  imports:
    - gravelamps
    - gravelamps.lensing.point
  commands:
    - pip check
    - gravelamps_inference --help
    - gravelamps_generate_lens --help
  requires:
    - pip

about:
  home: https://git.ligo.org/link/pre-merger-software/gravelamps
  summary: Software package designed for running template based analysis of lensed gravitational wave signals to determine the lens profile model. Built on top of the parameter estimation framework, Bilby, and arbitrary precision library arb
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mick-wright
